trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildDirectory: '$(Build.ArtifactStagingDirectory)/build'

steps:
- task: UseNode@2
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js dependencies'

- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    npm run build
  displayName: 'Build Project'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(buildDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publish Build Artifacts'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'YOUR_AZURE_SUBSCRIPTION_NAME'
    appName: 'YOUR_APP_NAME'
    package: '$(buildDirectory)/**/*.zip'
  displayName: 'Deploy to Azure Web App'

- script: echo "Build and Deployment Complete!"
  displayName: 'Final Step'
